server: 
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_qualification
    username: root
    password: yare1502
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
